services:
  postgres:
    image: postgres
    container_name: todolist-db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: unless-stopped

volumes:
  pgdata:
