"""remove unique constraint from name in task

Revision ID: 940d702b9066
Revises: fd2d5f99edbe
Create Date: 2025-12-06 20:39:24.324876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940d702b9066'
down_revision: Union[str, Sequence[str], None] = 'fd2d5f99edbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_name_key'), 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('tasks_name_key'), 'tasks', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
